PCHR-1119: Add the getDefaultEntity to the AbsenceType form class
After updating to CiviCRM 4.7, whenever we tried to add or edit an Absence Type,
we got this error:

Exception: "Cannot determine default entity. CRM_HRLeaveAndAbsences_Form_AbsenceType should implement getDefaultEntity()."

This was solved by adding the missing method, that overrides the one defined in
CRM_Core_Form.